name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dart_seq_hive_cache:
    path: ../
  dart_seq: ^2.0.0
  dart_seq_http_client: ^1.0.0
