name: dart_seq_hive_cache
description: An extension for `dart_seq` that provides a local database for log events using Hive
version: 0.0.1
homepage: https://github.com/ricardoboss/dart_seq_hive_cache

publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dart_seq:
    git:
      url: https://github.com/ricardoboss/dart_seq
      ref: main
  hive: ^2.2.3
  path_provider: ^2.0.15
