name: dart_seq_hive_cache
description: An extension for `dart_seq` that provides a local database for log events using Hive
version: 1.0.0-pre.1
homepage: https://github.com/ricardoboss/dart_seq_hive_cache

screenshots:
  - './doc/Screenshot 2024-03-20 050912.png'

environment:
  sdk: ^3.0.0

dependencies:
  dart_seq: ^1.0.0
  hive: ^2.2.3

dev_dependencies:
  strict: ^2.0.0
